<?php

namespace Gestion\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteTypeRepository extends EntityRepository
{
}
