<?php

namespace Gestion\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
	public function findAllMembresArray(){
		$result  = $this->createQueryBuilder('e')
               ->select('e')
               ->getQuery()
               ->getResult();
		$tabmembre = array();	   
		foreach($result as $membre){
			array_push($tabmembre,$membre);
		}		
			   
		return $tabmembre;
	}
}
