gestion_core:
    resource: "@GestionCoreBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /

#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery

#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media

#IMAGINE
_imagine:
    resource: .
    type:     imagine

thrace_media_backend:
    resource: "@ThraceMediaBundle/Resources/config/routing/backend.xml"
    prefix:   /admin

thrace_media_frontend:
    resource: "@ThraceMediaBundle/Resources/config/routing/frontend.xml"
    prefix:   /

